language: php

php:
  - 5.6
  - hhvm
  - 7

install: 
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
